C_COMPILER=g++
CXX_COMPILER=g++
ARCHIVER=ar

SOURCE_FILES=uthreads.cpp
OBJECT_FILES=$(SOURCE_FILES:.cpp=.o)

INCLUDE_PATHS=-I.
C_COMPILER_FLAGS = -Wall -std=c++11 -g $(INCLUDE_PATHS)
CXX_COMPILER_FLAGS = -Wall -std=c++11 -g $(INCLUDE_PATHS)

STATIC_LIB = libuthreads.a
BUILD_TARGETS = $(STATIC_LIB)

TAR_COMMAND=tar
TAR_OPTIONS=-cvf
TAR_FILE_NAME = ex2.tar
TAR_SOURCE_FILES=$(SOURCE_FILES) Makefile README

all: $(BUILD_TARGETS)

$(BUILD_TARGETS): $(OBJECT_FILES)
	$(ARCHIVER) rcs $@ $^

clean:
	$(RM) $(BUILD_TARGETS) $(OBJECT_FILES) *~ *core

depend:
	makedepend -- $(C_COMPILER_FLAGS) -- $(SOURCE_FILES)

tar:
	$(TAR_COMMAND) $(TAR_OPTIONS) $(TAR_FILE_NAME) $(TAR_SOURCE_FILES)